projects:
  TaskAppSyncAPI:
    schemaPath: app/src/main/graphql/schema.json
    includes:
      - mutations
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: ''
        generatedFileName: ''
        docsFilePath: app/src/main/graphql/com/amazonaws/amplify/generated/graphql
        region: us-west-2
        apiId: uauksevt2rdv7lxlncgovn6mv4
        maxDepth: 2
extensions:
  amplify:
    version: 3
